secrets:
  ssh-private-key:
    file: secrets/id_ed25519_sym

services:
  Lightbulb-Automation:
    image: ghcr.io/project-chip/chip-build:174
    #stdin_open: true
    #tty: true
    #command: /bin/bash
    #command: /bin/sh -c 'echo "hello $$HOSTNAME"'
    volumes:
     - type: bind
       source: ../connectedhomeip
       target: /connectedhomeip
    secrets:
      - source: ssh-private-key
        target: /root/.ssh/id_ed25519