secrets:
  ssh-private-key:
    file: secrets/id_ed25519_sym

services:
  Lightbulb-Automation:
    image: chip-local-dev:174
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - type: bind
       source: ../connectedhomeip
       target: /connectedhomeip
    secrets:
      - source: ssh-private-key
        target: /root/.ssh/id_ed25519